freeCodeCamp/demo-projects

- request-header-parser-microservice/README.md
- request-header-parser-microservice/views/index.html
> fix: update urls to match subdomain

- issue-tracker/README.md
- metric-imperial-converter/README.md
- metric-imperial-converter/views/index.html
- personal-library/README.md
- personal-library/views/index.html
> fix: remove helmet user stories for QA projects

- url-shortener-microservice/README.md
Related to Issue: https://github.com/freeCodeCamp/freeCodeCamp/issues/39721
As is, easy-peasy-lemon-squeezy.
> feat: remove user stories from url-shortener

- exercise-tracker/README.md
Related to: https://github.com/freeCodeCamp/freeCodeCamp/issues/39721
Wait until we have added user stories to learn to merge this.
> fix: remove exercise tracker user stories

- scripts/twitch-proxy/README.md
- scripts/twitch-proxy/package-lock.json
- scripts/twitch-proxy/package.json
- scripts/twitch-proxy/update-and-reload-twitch-proxy.sh
- scripts/twitch-proxy/updateApiKey.js
Adds scripts and a README file with a brief explanation about how to run everything with pm2. Might be a bit overkill, so let me know if there's anything I can change.
> feat: add scripts to update and restart twitch proxy project

- issue-tracker/assertion-analyser.js
- issue-tracker/models/issue.js
- issue-tracker/package-lock.json
- issue-tracker/package.json
- issue-tracker/routes/api.js
- issue-tracker/routes/fcctesting.js
- issue-tracker/sample.env
- issue-tracker/server.js
- issue-tracker/test-runner.js
- issue-tracker/tests/2_functional-tests.js
- issue-tracker/views/index.html
- issue-tracker/views/issue.html
@nhcarrigan and I refactored the tests and user stories for this project as described here:
freeCodeCamp/freeCodeCamp#39627
PR for the Boilerplate here:
https://github.com/freeCodeCamp/boilerplate-project-issuetracker/pull/13
> Issue Tracker Project - Refactored

- timestamp-microservice/package-lock.json
- timestamp-microservice/package.json
- timestamp-microservice/server.js
- timestamp-microservice/views/index.html
Checklist:
Partially addresses https://github.com/freeCodeCamp/freeCodeCamp/issues/41529
Live example with these changes: https://timestamp-update.scissorsneedfoo.repl.co
> fix: support new and legacy endpoints for Timestamp MS project, update packages

- exercise-tracker/models/exercises.js
- exercise-tracker/package-lock.json
- exercise-tracker/package.json
- exercise-tracker/routes/api.js
- exercise-tracker/server.js
Checklist:
Partially addresses https://github.com/freeCodeCamp/freeCodeCamp/issues/41529
Live example with these changes: https://exercise-tracker-update.scissorsneedfoo.repl.co
> fix: update demo exercise tracker project endpoints

- exercise-tracker/views/index.html
> fix: add missing updates to the exercise tracker project page

- build-a-pinterest-clone/views/index.html
- file-metadata-microservice/views/index.html
- request-header-parser-microservice/views/index.html
Checklist:
Closes https://github.com/freeCodeCamp/freeCodeCamp/issues/38540
Replaces the remaining green favicons with the indigo version.
> fix: replace favicons

- anonymous-message-board/controllers/replyHandler.js
Checklist:
Related to comment: https://github.com/freeCodeCamp/freeCodeCamp/pull/43041#pullrequestreview-719650706
> fix(message board): make bumped on date same as reply creation

- exercise-tracker/views/index.html
Checklist:
Related to https://github.com/freeCodeCamp/boilerplate-project-exercisetracker/pull/53
> fix: update exercise tracker id and favicon

- package-lock.json
- package.json
pm2 is one of the rare things you do want to install globally.  It might
be fine to also install it locally, but there's potential for conflict.
> chore: remove pm2

- apps/manage-a-book-trading-club/package.json
- package-lock.json
- chore: remove eslint, regenerate package-lock
- chore: update pug
> chore: clean up packages and update pug

- apps/stock-price-checker-proxy/api/v1.js
- apps/stock-price-checker-proxy/package.json
- apps/twitch-proxy/package.json
- apps/twitch-proxy/server.js
- package-lock.json
nedb is unmaintained, but the seald fork is being updated regularly.
> chore: migrate to @seald-io/nedb

- .github/workflows/node-ci.yml
> chore(tools): lock ci to node 16

- apps/image-search-abstraction-layer/api.js
This project was missed when I created https://github.com/freeCodeCamp/demo-projects/pull/140
> fix: mongo 3 for image-search-abstraction-layer

- apps/issue-tracker/routes/api.js
- apps/issue-tracker/tests/2_functional-tests.js
Checklist:
Thanks to @c-ehrlich for highlighting this issue.
> fix: handle non-ObjectId PUTs to issue-tracker

- CONTRIBUTE.md
> docs: add section about node version updates

- renovate.json
Moving to a standardized set of rules we have been using elsewhere.
> chore: use global config repo

- CONTRIBUTE.md
> Add that package.json needs to be updated adding a new projecy

- CONTRIBUTE.md
> chore: update docs

- CONTRIBUTE.md
- scripts/update.sh
> chore: update docs and script

- CONTRIBUTE.md
> docs: add project structure outline + bundler info

- apps/anonymous-message-board/controllers/replyHandler.js
- apps/anonymous-message-board/controllers/threadHandler.js
- apps/anonymous-message-board/package.json
- package-lock.json
Checklist:
Closes #XXXXX
Catches a vulnerability reported on our Discord by @Tezcatlipoca0000.
I can't get the app to work locally but this *should* resolve the issue. @raisedadead you should see a copy of the report in our inbox too.
> fix: sanitise html

- CONTRIBUTE.md
Checklist:
_This took hours to debug, and has probably caused thousands of developers to have headaches. Really, it is surprising GitHub did not burst into flames with this._
> fix(docs): update biggest typoe ever

- apps/sudoku-solver/controllers/sudoku-solver.js
Checklist:
Closes #48307
https://github.com/freeCodeCamp/freeCodeCamp/issues/48307
Closes #48687
https://github.com/freeCodeCamp/freeCodeCamp/issues/48687
Still needs algorithm improvements though.
> fix(sudoku-solver): increase recursion limit 

- apps/stock-price-checker/controllers/stockHandler.js
> chore(stock-price-checker): check input

- scripts/create-caddyfile.js
Checklist:
This updates the `create-caddyfile.js` script to add a `/ping` route to www.freecodecamp.rocks for health checks.
> feat: add health check to create-caddyfile.js

- apps/chart-the-stock-market/package-lock.json
- apps/chart-the-stock-market/package.json
- apps/chart-the-stock-market/public/index.html
- apps/secure-real-time-multiplayer-game/package-lock.json
- apps/secure-real-time-multiplayer-game/package.json
- apps/secure-real-time-multiplayer-game/server.js
> chore: update socketio

- apps/voting-app/app.js
- apps/voting-app/package-lock.json
- apps/voting-app/package.json
- apps/voting-app/views/index.ejs
- apps/voting-app/views/login.ejs
- apps/voting-app/views/mypolls.ejs
- apps/voting-app/views/newpoll.ejs
- apps/voting-app/views/signup.ejs
- apps/voting-app/views/singlepoll.ejs
**What does**:
- Major update `apps/voting-app` `ejs` dep to `3`
- Necessary `.ejs` file changes for major change
- Added error to `mongo.connect` callback, because I needed it for debugging
Sorry about some of the files having formatting changes.
> chore(voting-app): update ejs

- apps/cash-register/server.js
> feat: add a status endpoint for the cash register

- apps/25--5-clock/server.js
Checklist:
Related to #484 
I closed the old PR because of the white space issues.
> feat: add a status endpoint for the 25-5 clock

- apps/drum-machine/server.js
> feat: add a status check to the drum machine

- apps/random-quote-machine/server.js
> feat: add a status check to the random quote machine

- apps/markdown-previewer/server.js
> feat: add a status check to the markdown previewer

- apps/tribute-page/server.js
> feat: add a status check to the tribute page

- apps/palindrome-checker/server.js
> feat: add a status check to the palindrome checker

- apps/pokeapi-proxy/server.mjs
> feat: add a status check to the pokeapi-proxy

- apps/file-metadata-microservice/server.js
> feat: live check on file metadata microservice

- apps/forum-proxy/server.mjs
> feat: live service check on forum-proxy

- apps/american-british-translator/server.js
Checklist:
Related to #484 
This is what I meant by https://github.com/freeCodeCamp/demo-projects/issues/497. It makes my changes look really off-putting after I used `prettier`.  If we get to the bottom of it, the issue I opened can be properly closed.
> feat: add a live service check to the american-british translator

- apps/secure-real-time-multiplayer-game/server.js
> feat: live service check for real time mutliplayer app

- apps/stock-price-checker-proxy/server.js
> feat: live service check on stock price checker proxy

- apps/cash-register/index.html
> fix: close main tag in cash register app

- .lintstagedrc.js
- apps/weather-proxy/server.js
Checklist:
Related to #484
Things were moved to another folder and I discovered a slight issue. It seems like the lint staging pattern I was using needed a slight adjustment to work with spaces in the file path.
> feat: live service check weather proxy

- apps/survey-form/server.js
> feat: add liveliness check endpoint for survey form

- apps/build-a-pinterest-clone/server.js
Checklist:
Related to https://github.com/freeCodeCamp/demo-projects/issues/484
> feat: live check for pininterest clone

- apps/choropleth-map/server.js
> feat: live check for choropleth map app

- apps/exercise-tracker/server.js
> feat: live check for exercise tracker

- apps/url-shortener-microservice/server.js
> feat: create a live check for the url shortener

- apps/timestamp-microservice/server.js
> feat: Live check on timestamp microservice

- apps/image-search-abstraction-layer/api.js
> feat: live check on image-search abstraction layer

- apps/heat-map/server.js
> feat: live check on heat map

- apps/issue-tracker/server.js
> feat: live check on issue tracker

- apps/metric-imperial-converter/server.js
> feat: live check on metric imperial converter

- apps/manage-a-book-trading-club/app/routes.js
> feat: live check on book trading club

- apps/p2p-video-chat-application/server.js
> feat: live check on p2p video chat app

- apps/pokemon-search-app/server.js
> feat: live check on pokemon search app

- apps/personal-portfolio/server.js
> feat: live check on personal portfolio

- apps/personal-library/server.js
> feat: live check on personal library

- apps/roman-numeral-converter/server.js
> feat: live check on roman numeral converter

- apps/scatterplot-graph/server.js
> feat: live check on scatterplot graph

- apps/timestamp-microservice/views/index.html
Checklist:
Closes #52467
Link to the Issue description - https://github.com/freeCodeCamp/freeCodeCamp/issues/52467
> Fixed HTML heading levels

- apps/technical-documentation-page/server.js
> feat: live check on technical documentation page

- apps/telephone-number-validator/server.js
> feat: live check on telephone number validator

- apps/treemap-diagram/server.js
> feat: live check on treemap diagram

- apps/cash-register/index.html
- apps/cash-register/public/script.js
- apps/cash-register/public/styles.css
- apps/palindrome-checker/index.html
- apps/palindrome-checker/public/script.js
- apps/palindrome-checker/public/styles.css
- apps/pokemon-search-app/index.html
- apps/pokemon-search-app/public/script.js
- apps/pokemon-search-app/public/styles.css
- apps/roman-numeral-converter/index.html
- apps/roman-numeral-converter/public/styles.css
- apps/telephone-number-validator/index.html
- apps/telephone-number-validator/public/script.js
- apps/telephone-number-validator/public/styles.css
Checklist:
Related to https://github.com/freeCodeCamp/freeCodeCamp/pull/52370
> fix: updates to required JS projects

- apps/pokeapi-proxy/public/index.html
> fix: typo in pokeapi description

- apps/cash-register/public/script.js
Checklist:
References: 
- [#52929](https://github.com/freeCodeCamp/freeCodeCamp/pull/52929)
- [#52688](https://github.com/freeCodeCamp/freeCodeCamp/issues/52688)
> fix(Challenge): fixed the solution of cash register

- apps/rpg-creature-search-app/public/script.js
Checklist:
Closes #XXXXX
The demo is using the wrong URL for its fetch.
https://rpg-creature-api.freecodecamp.rocks
> fix(demo): use correct URL in fetch

- README.md
(and add some spaces in the file for consistency)
Checklist:
Related to: https://github.com/freeCodeCamp/freeCodeCamp/issues/59021
> fix: use new links and projects in readme
