freeCodeCamp/demo-projects

.gitignore, build-a-pinterest-clone/package.json, forum-proxy/package.json, manage-a-book-trading-club/package.json, p2p-video-chat-application/package.json, twitch-proxy/package-lock.json, twitch-proxy/package.json, weather-proxy/package.json
This adds a package-lock file for the twitch proxy project
Changes the start script of all applicable projects to use server.js instead of index.js, since we renamed all of those.
It also adds a few things to the top level gitignore that were removed from individual project gitignore files - see photo:
=> fix: change start scripts + add package-lock + gitignore

timestamp-microservice/README.md, timestamp-microservice/public/style.css, timestamp-microservice/views/index.html
Related to: https://github.com/freeCodeCamp/freeCodeCamp/issues/39721
The unused css was used in the index.html file - the user stories were already removed from there so the css wasn't being used anymore. 
Wait until we have added user stories to learn to merge this.
=> fix: remove user stories and some unused css

request-header-parser-microservice/README.md, request-header-parser-microservice/public/style.css
Related to: https://github.com/freeCodeCamp/freeCodeCamp/issues/39721
The css was used for elements that described the user stories in the index.html file - those elements were removed with another PR
Wait until we have added user stories to learn to merge this.
=> fix: remove readme and unused css

stock-price-checker/views/index.html
The requirement for `price` is for it to be a number, so the example return shown should not be a string. I did this edit directly in the file, but hopefully, that's OK.
As a separate issue, we also need to change the User story https://github.com/freeCodeCamp/freeCodeCamp/pull/40218#pullrequestreview-538375840
=> fix: Show correct return type for price in example usage

sudoku-solver/controllers/sudoku-solver.js, sudoku-solver/routes/api.js
* Changes handling of check for value that already is in puzzle under checked coordinate.
* Project with changes tested on repl.it and against project page tests on local fork of freeCodeCamp.
Related to https://github.com/freeCodeCamp/freeCodeCamp/issues/40359 and https://github.com/freeCodeCamp/freeCodeCamp/pull/41225
=> fix: clear target cell in puzzle before value try

exercise-tracker/views/index.html
- Removes part of exercise log description that's not relevant in new version of url route.
- Related to https://github.com/freeCodeCamp/freeCodeCamp/pull/41786 and https://github.com/freeCodeCamp/boilerplate-project-exercisetracker/pull/51
Checklist:
=> fix: remove not used part of log url description

anonymous-message-board/controllers/replyHandler.js, anonymous-message-board/controllers/threadHandler.js
Checklist:
This ties in to https://github.com/freeCodeCamp/freeCodeCamp/pull/41932.
The database queries were already attempting to hide the `reported` and `delete_password` fields but the syntax was incorrect so the fields were still being fetched.
=> fix: hide fields

renovate.json
I think we want to do this, since we want reproducibility (exactly the same versions in CI as in production), not flexibility.
@nhcarrigan I noticed https://github.com/freeCodeCamp/demo-projects/pull/102 going in and figured pinning is probably the way to go.
=> fix: pin all dependencies

apps/sudoku-solver/controllers/sudoku-solver.js
Checklist:
Closes #XXXXX
In the current state, the recursion get stuck in a loop if an unsolvable puzzle string is submitted. @ojeytonwilliams and I discussed an approach to fixing this with an arbitrary timeout, but after further thought I decided counting the recursive calls might be better.
A quick Google search gave me the "world's hardest sudoku", which the solver took 49000+ recursive calls to solve. By counting and capping the recursive calls at 50000, this PR will add an assumption that additional calls mean the puzzle is unsolvable and back out of the recursion.
Passing an unsolvable string with this change no longer locks up the server, but instead properly displays "puzzle cannot be solved" in the front end.
=> fix: avoid endless recursion

apps/sudoku-solver/routes/api.js
Shows the correct response when a user attempts to submit `value=0` to `/api/check`.
```
curl -X POST https://sudoku-solver.freecodecamp.rocks/api/check 
-H "Content-Type: application/x-www-form-urlencoded"
-d 'puzzle=.................................................................................&coordinate=A1&value=0' 
```
```json
{
"valid": false,
"conflict": [
"row",
"column",
"region"
]
}
```
```json
{
"error": "Invalid value"
}
```
Checklist:
=> Only accept 1-9 for /api/check value input

apps/image-search-abstraction-layer/api.js
Checklist:
Addresses https://github.com/freeCodeCamp/freeCodeCamp/issues/43518
The main fix is moving `db.close()` inside the `.toArray()` method in the `getRecent` function.
All the other changes are cosmetic.
=> fix: image search abstraction layer recent searches

apps/heat-map/public/script.js
Checklist:
Closes https://github.com/freeCodeCamp/freeCodeCamp/issues/47073
---
- Depending on the local time axes can start on the different value (see occurrences in the linked issue). `timeFormat` method interprets data as being in the local time, `utcFormat` uses _Coordinated Universal Time (UTC)_ for that.
- The third occurrence `timeFormat('%Y - %B')` did not seem to impact tests, but I've changed it for consistency.
- Example with applied changes can be found at https://codepen.io/sanityto/full/gOKJQae
=> fix: heat map axes affected by local time

apps/javascript-calculator/client/index.jsx
Checklist:
- [ x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x ] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)
Partially addresses [#49045](https://github.com/freeCodeCamp/freeCodeCamp/issues/49045)
I included the closing number for issue 49045 because while working on it, I could not replicate that specific issue. In the process, I discovered that the minus operator was showing as a zero.  I changed the character based on the warning and has seemed to fix the issue. 
Also was receiving a warning due to missing rel-tag, so I included that as well.
=> fix(javascript-calculator): adjust minus unicode, add noreferrer

apps/sudoku-solver/controllers/sudoku-solver.js
* fix: check whether the input is a valid board state in `SudokuSolver.validate` before attempting to solve it.
Closes freeCodeCamp/freeCodeCamp#48307
---
Please add the `hacktoberfest-accepted` label to this PR if you decide to merge it. Thanks!
=> fix: correctly handle invalid input in sudoku-solver

apps/javascript-calculator/server.js
=> feat: add a status check to the javascript calculator

.gitignore, .husky/pre-commit, .lintstagedrc.js, .prettierignore, package-lock.json, package.json
Checklist:
Closes #497
This adds a husky pre-commit hook and automatically lints all committed files with lint-staged.
=> feat: configure formatting tools

apps/anonymous-message-board/server.js
Checklist:
Related to https://github.com/freeCodeCamp/demo-projects/issues/484
=> feat: add a live service check to the anon message board

apps/chart-the-stock-market/index.js
=> feat: live check for chart stock market app

apps/twitch-proxy/server.js
=> feat: add a live check for the twitch proxy

scripts/create-caddyfile.js
Checklist:
Closes https://github.com/freeCodeCamp/demo-projects/issues/535
This adds an exception for the `25--5-clock` subdomain in the Caddyfile generator script to get around the bug we discovered some time ago where two consecutive numbers don't work as a subdomain for some reason.
This fix, along with the redirect on Cloudflare from `25--5-clock.freecodecamp.rocks` to `clock.freecodecamp.rocks`, should take care of the issue above where visiting `25--5-clock.freecodecamp.rocks` leads to an error page.
=> fix: 25-5 clock Caddyfile workaround

apps/stock-price-checker/routes/api.js
=> feat: live check on stock-price-checker

test/ports.test.js
Checklist:
Related to #490
This uses the existing for loops in the project statuses to perform a basic health test on all the apps. Though I'd like to see something akin to tests that main curriculum has in order to ensure that they meet all the same standards.
=> feat: health check tests

apps/pokemon-search-app/public/styles.css, apps/roman-numeral-converter/public/styles.css
Checklist:
Partially addresses https://github.com/freeCodeCamp/freeCodeCamp/issues/52709.
1. The `outline: none;` CSS property of the `button` element was removed so it will be keyboard-focusable and complying the [WCAG SC 2.1.1](https://www.w3.org/WAI/WCAG21/Understanding/keyboard.html).
2. Also, removing `outline: none;` and `outline-style: none;` of `input` element and applying the custom outline styles to the `input` and `button` elements with using the `:focus-visible` pseudo-class so the outline will be sufficiently visible for people who is visually impaired or have low vision and complying the [WCAG SC 2.4.7](https://www.w3.org/WAI/WCAG21/Understanding/focus-visible.html), with referencing the [technique G195](https://www.w3.org/WAI/WCAG21/Techniques/general/G195). After …
=> fix(a11y): make the input and button elements accessible

apps/cash-register/public/script.js
Checklist:
Closes https://github.com/freeCodeCamp/freeCodeCamp/issues/54423
When 141.77 was entered as the cash input, "Status: INSUFFICIENT_FUNDS" would be outputted. This is now fixed
=> fix: issue with cash register input check, replace ">" with ">="

scripts/create-caddyfile.js
This PR updates the Caddyfile script generator to use the `tls internal` directive with Caddy to allow for full SSL behaviour from Cloudflare. We used to use LE-based certificates but they are redundant since we use Cloudflare.
=> feat: use tls internal for Caddy

apps/pokeapi-proxy/api/pokemon/pokemon.handlers.mjs
Checklist:
Closes https://github.com/freeCodeCamp/demo-projects/issues/597
This PR simplifies handling of the API resource protocol so resource links on the `/api/pokemon` endpoint only use HTTP when the project is running locally, and use HTTPS in all other cases.
I believe it's still possible for someone to set the headers to `localhost:<port>` when sending a request to the API, which would mean that the links at `/api/pokemon` would be HTTP rather than HTTPS, but I doubt it will be an issue for this project. At this point, learners should just be using `fetch()` without setting any headers.
=> fix: simplify protocol handling

.eslintrc.json, apps/cash-register/public/script.js
Checklist:
Closes #559
- - -
- Solution updated to version from https://github.com/freeCodeCamp/freeCodeCamp/pull/55066.
- Added ignored patterns to `.eslintrc.json`, if needed I can use comment to two, currently, affected lines, or create separate PR.
=> fix: improve cash register precision

.gitpod.yml, apps/twitch-proxy/package.json, jest.config.js, test/jest-utils.js, test/ports.test.js, test/twitch-proxy.test.js
Checklist:
Related to #490
This adds a few tests to ensure the Twitch Proxy data routes are still functioning correctly.
=> chore: create twitch proxy tests

apps/palindrome-checker/public/script.js
Checklist:
Closes #XXXXX
Please also see an email I sent to `possible-security-issue at freecodecamp dot org`.
Interpolating user input into `innerHTML` sink can lead to security issues.
This pull request changes the `innerHTML` sink to `innerText` in the Palindrome Checker project, which fixes the vulnerability.
This is my first contribution to freeCodeCamp, let me know if anything could be improved! I also wanted to extend my thanks to the freeCodeCamp team for creating such a great learning platform 🙌
=> fix: Remove innerHTML sink in Palindrome Checker

apps/image-search-abstraction-layer/public/imageSearch.js
Checklist:
Please also see an email I sent to `possible-security-issue at freecodecamp dot org`.
To fix this issue, we need to ensure that any user input is properly sanitized or escaped before being used in a context where it can be interpreted as HTML. In this case, we should use `textContent` instead of `innerHTML` to avoid interpreting the text as HTML. Additionally, we should ensure that the URL is properly encoded.
- Replace `urlDiv.innerHTML = url;` with `urlDiv.textContent = url;` to prevent the text from being interpreted as HTML.
- Ensure that the URL is properly encoded using `encodeURIComponent` for the query parameters.
=>  fix: DOM text reinterpreted as HTML leading to self-XSS
